//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnihovnaDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_cz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_cz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnihovnaDemo.Resources.Resources-cz", typeof(Resources_cz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autor.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno autora.
        /// </summary>
        internal static string AuthorsName {
            get {
                return ResourceManager.GetString("AuthorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knížka.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID knížky.
        /// </summary>
        internal static string BookId {
            get {
                return ResourceManager.GetString("BookId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knížky.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název knížky.
        /// </summary>
        internal static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vypůjčení.
        /// </summary>
        internal static string DateOfBorrow {
            get {
                return ResourceManager.GetString("DateOfBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vypůjčení.
        /// </summary>
        internal static string DateOfBorrowing {
            get {
                return ResourceManager.GetString("DateOfBorrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vrácení.
        /// </summary>
        internal static string DateOfReturn {
            get {
                return ResourceManager.GetString("DateOfReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editovat.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editovat knížku.
        /// </summary>
        internal static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editvat uživatele.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit knížku.
        /// </summary>
        internal static string InsertBook {
            get {
                return ResourceManager.GetString("InsertBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit vypůjčku.
        /// </summary>
        internal static string InsertLoan {
            get {
                return ResourceManager.GetString("InsertLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit uživatele.
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je uživatel administrátor?.
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypůjčeno uživetelem.
        /// </summary>
        internal static string LendedBy {
            get {
                return ResourceManager.GetString("LendedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vypůjčky.
        /// </summary>
        internal static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet knih v knihovně.
        /// </summary>
        internal static string NumberOfBook {
            get {
                return ResourceManager.GetString("NumberOfBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vrácení.
        /// </summary>
        internal static string Retur {
            get {
                return ResourceManager.GetString("Retur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmono knížky.
        /// </summary>
        internal static string TitleBook {
            get {
                return ResourceManager.GetString("TitleBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uživatel.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID uživatele.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
